update

diff --git a/convert_clinvar b/convert_clinvar
--- a/convert_clinvar
+++ b/convert_clinvar
@@ -9,7 +9,7 @@
 # Property
 ##
 BASE_DIR=/data
-WORK_DIR=./clinvar_latest
+WORK_DIR=/work
 XSD_URL=https://ftp.ncbi.nlm.nih.gov/pub/clinvar/xsd_public/clinvar_variation/variation_archive.xsd
 XML_URL=https://ftp.ncbi.nlm.nih.gov/pub/clinvar/xml/clinvar_variation/ClinVarVariationRelease_00-latest.xml.gz
 BASE_URL=https://ftp.ncbi.nlm.nih.gov/pub/clinvar/xml/clinvar_variation/
@@ -17,18 +17,17 @@ TEMP_HTML=clinvar.html
 FILE_TEMPLATE=ClinVarVariationRelease_00-latest
 
 
-cd ${BASE_DIR}
+cd ${WORK_DIR}
 
 # check if last data exisits
-if [ -d ${WORK_DIR} ]; then
+if [ -e ${FILE_TEMPLATE}.xml.gz  ]; then
 
 	# check if md5file exists 
-        wget --spider -q ${XML_URL}.md5
+        wget --spider -q ${XML_URL}.md5 2> /dev/stdout
         md5_exist=$?
         if [ ${md5_exist} = 0 ];then
-                cd ${WORK_DIR}
                 test -e ${FILE_TEMPLATE}.xml.gz.md5 && rm ${FILE_TEMPLATE}.xml.gz.md5
-                wget -q ${XML_URL}.md5
+                wget -q ${XML_URL}.md5 2> /dev/stdout
                 md5sum ${FILE_TEMPLATE}.xml.gz && md5sum -c ${FILE_TEMPLATE}.xml.gz.md5
                 is_update=$?
 
@@ -38,13 +37,12 @@ if [ -d ${WORK_DIR} ]; then
 			echo "have already latest version"
                         exit 0
                 else
-                        echo "new data exist"
-			echo "perform update "
-                        cd ../
+                	rm -rf ${FILE_TEMPLATE}.xml.gz.md5
+			rm -rf ${FILE_TEMPLATE}.xml.gz
                 fi
 
         else
-                echo "MD5 file not found"
+                echo "MD5 file not found" >&2
                 exit 1
         fi
 fi
@@ -52,34 +50,28 @@ fi
 
 
 # check if data exists
-wget --spider -q ${XSD_URL}
+wget --spider -q ${XSD_URL} 2> /dev/stdout
 xsd_exist=$?
-wget --spider -q ${XML_URL}
+wget --spider -q ${XML_URL} 2> /dev/stdout
 xml_exist=$?
 if [ ${xsd_exist} = 0 -a ${xml_exist} = 0 ]; then
 
-        # remove last data
-        test -d ${WORK_DIR} && rm -rf ${WORK_DIR}
+	#echo "download XML and XSD files"
+        wget  ${XSD_URL} 2> /dev/stdout
+        wget  ${XML_URL} 2> /dev/stdout
 
-        # make directry and file download
-        mkdir ${WORK_DIR}
-        cd ${WORK_DIR}
-	echo "download XML and XSD files"
-        wget -q ${XSD_URL}
-        wget -q ${XML_URL}
+	cd ${BASE_DIR}
+        #echo "excute split"
+        /clinvar-rdf/bin/split ${WORK_DIR}/${FILE_TEMPLATE}.xml.gz
 
-        echo "excute split"
-        /clinvar-rdf/bin/split ${FILE_TEMPLATE}.xml.gz
+        #echo "complete split . convert into rdf"
+        ls ${FILE_TEMPLATE}_*.xml.gz | xargs -n1 -P10 -I{} bash -c "f={}; zcat \${f} | /clinvar-rdf/docker-entrypoint.sh convert --xsd $(ls /work/*.xsd) 2>\${f%%.*}.log | gzip -c >\${f%%.*}.ttl.gz"
+        rm ${FILE_TEMPLATE}_*.xml.gz && rm *.log 
 
-        echo "complete split . convert into rdf"
-        ls ${FILE_TEMPLATE}_*.xml.gz | xargs -n1 -P10 -I{} bash -c "f={}; zcat \${f} | /docker-entrypoint.sh convert --xsd $(ls *.xsd) 2>\${f%%.*}.log | gzip -c >\${f%%.*}.ttl.gz"
-        rm ${FILE_TEMPLATE}_*.xml.gz && rm *.log
-	cd ../ && chmod -R 777 ./
-	echo "complete convert"
+	chmod 777 $(ls) 
 
 else
-        echo "clinvar data not found"
+        echo "clinvar data not found" >&2
         exit 1
 fi
-
 
